// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/07/23, 13:48:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/payfastdeveloper/Documents/projects/ordo/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/plugins/**/*.{js,ts,mjs}","/home/payfastdeveloper/Documents/projects/ordo/fe/composables/**/*.{js,ts,mjs}","/home/payfastdeveloper/Documents/projects/ordo/fe/utils/**/*.{js,ts,mjs}","/home/payfastdeveloper/Documents/projects/ordo/fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/payfastdeveloper/Documents/projects/ordo/fe/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;